name: Security Audit with Prowler

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Set up Python environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --upgrade pip
        pip3 install prowler
        pip3 install pyOpenSSL --upgrade 
        pip3 install boto3 botocore

    - name: Run Prowler
      run: |
        prowler -f json > prowler_output.json
      continue-on-error: true

    - name: Check Prowler results
      id: check-results
      run: |
        if grep -q "\"result\": \"FAIL\"" prowler_output.json; then
          echo "iam_audit_failed=true" >> $GITHUB_ENV
        else
          echo "iam_audit_failed=false" >> $GITHUB_ENV
        fi

    - name: Create Jira ticket on policy violation
      if: env.iam_audit_failed == 'true'
      env:
        JIRA_USER: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        curl -D- \
          -u $JIRA_USER:$JIRA_API_TOKEN \
          -X POST \
          --data '{
            "fields": {
              "project": {
                "key": "'$JIRA_PROJECT_KEY'"
              },
              "summary": "IAM Policy Violation Detected",
              "description": "'"${COMMIT_MESSAGE}"' - IAM policy violation detected in the latest deployment. Please review and remediate.",
              "issuetype": {
                "name": "Task"
              }
            }
          }' \
          -H "Content-Type: application/json" \
          $JIRA_URL/rest/api/2/issue/
