name: Create Jira Ticket on Commit

on:
  push:
    branches:
      - main

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Jira ticket
      env:
        JIRA_USER: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY: 'KAN'  # Replace with your Jira project key
        JIRA_URL: 'https://anurodhacharya10.atlassian.net/'  # Replace with your Jira instance URL
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        curl -D- \
          -u $JIRA_USER:$JIRA_API_TOKEN \
          -X POST \
          --data '{
            "fields": {
              "project": {
                "key": "'$JIRA_PROJECT_KEY'"
              },
              "summary": "New Commit to GitHub Repository",
              "description": "'"${COMMIT_MESSAGE}"'",
              "issuetype": {
                "name": "Task"
              }
            }
          }' \
          -H "Content-Type: application/json" \
          $JIRA_URL/rest/api/2/issue/
